# Generated by Django 4.1.6 on 2023-02-15 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movie_added_by_movieorder_movie_orders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieorder",
            old_name="movies",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="movieorder",
            old_name="users",
            new_name="user",
        ),
    ]
