# Generated by Django 4.1.6 on 2023-02-16 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0003_rename_movies_movieorder_movie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies_added",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="added_by",
            field=models.CharField(max_length=127),
        ),
    ]
